---
title: "IITA Genomic Selection 2020"
site: workflowr::wflow_site
date: "2020-September"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

# Summary

Objective of this analysis is to refresh the IITA genomic predictions for all available germplasm, but especially adding the 45 trials listed by Ismail Rabbi on Sep. 14, 2020 (printed below). Clones are already planted in a mixed crossing block in Ubiaja and the new set of GEBV and GETGV will be used for selecting parents and crosses. 

We may try optimal contributions. For now skip cross-validation.

# September 2020 Analyses

1. [Prepare a training dataset](01-cleanTPdata.html): Download data from DB, "Clean" and format DB data.
2. [Curate by trait-trial](02-curateByTrial.html): Model each trait-trial separately, remove outliers, get BLUPs.
3. [Get BLUPs combining all trial data](03-GetBLUPs.html): Combine data from all trait-trials to get BLUPs for downstream genomic prediction.
    * Two versions of BLUPs produced (and later compared in next step) to determine _best_ procedure
4. [Check prediction accuracy](04-CrossValidation.html): Evaluate prediction accuracy with cross-validation.
    * Compare versions of BLUPs in terms of prediction accuracy. Required custom cross-validation code to ensure common train-test folds compared across methods.
5. [Genomic prediction](05-GetGBLUPs.html): Predict _genomic_ BLUPs (GEBV and GETGV) for all selection candidates using all available data.
6. [Results](06-Results.html): New home for plots and other results.

# December 2020 Analyses

1. [Prepare a training dataset](07-cleanTPdata_Dec2020.html): Freshly download all 2018-2020 trials. Combine rest of data and re-run "cleaning" and formatting pipeline.
2. [Get BLUPs combining all trial data](08-GetBLUPs_Dec2020.html): Detect experimental designs, Combine data from all trait-trials to get BLUPs for downstream genomic predictions. 
3. [Genomic prediction](09-GetGBLUPs_Dec2020.html): Predict **GETGV** specifically, for all selection candidates using all available data.
4. [Estimate rate of genetic gain](06-Results.html#rate_of_gain): 

# Other details

From Ismail Rabbi on 14 Sep. 2020:  

> We finished uploading to cassavabase the trials harvested so far. A few trials remain but we cant wait for them since flowering in Ubiaja is kicking in.

```{r, layout="l-body-outset", message=FALSE, warning=FALSE}
rmarkdown::paged_table(readr::read_csv(here::here("data","2019_GS_PhenoUpload.csv")))
```
